apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicea.fullname" . }}
  labels:
    app: {{ include "servicea.name" . }}
    chart: {{ include "servicea.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "servicea.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "servicea.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PORT
          value: "{{ .Values.env.port }}"
        ports:
        - containerPort: {{ .Values.env.port }}
        args: ["node", "serviceA.js"]