apiVersion: v1
kind: Service
metadata:
  name: {{ include "servicec.fullname" . }}
  labels:
    app: {{ include "servicec.name" . }}
    chart: {{ include "servicec.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3000
    targetPort: {{ .Values.env.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "servicec.name" . }}
    release: {{ .Release.Name }}
